name: visual_notes
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  #StateManagement
  flutter_riverpod: ^2.2.0

  #Ecosystem
  get: ^4.6.5

  #Responsive
  flutter_screenutil: ^5.6.1

  #LocalStorage
  path: ^1.8.2
  path_provider: ^2.0.13
  shared_preferences: ^2.0.18
  sqflite: ^2.2.5
  image_picker: ^0.8.6+3

  #Images
  lottie: ^2.2.0

  #Utils
  intl: ^0.17.0
  flutter_fadein: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  mockito: ^5.3.2
  flutter_lints: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.18

flutter_icons:
  image_path_android: "assets/images/core/icon.png"
  image_path_ios: "assets/images/core/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#58b9f0"

flutter_native_splash:
  background_image: "assets/images/welcome/splash_light.png"
  background_image_dark: "assets/images/welcome/splash_dark.png"
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/json/
    - assets/images/welcome/
    - assets/images/core/
    - assets/images/core/dialog_widget_icons/
    - assets/images/app_icons/
    - assets/images/app_icons/screens_icons/
    - assets/images/app_icons/languages_icons/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins.ttf
        - asset: assets/fonts/poppins_bold.ttf
          weight: 900
    - family: tajawal
      fonts:
        - asset: assets/fonts/tajawal.ttf
        - asset: assets/fonts/tajawal_bold.ttf
          weight: 900