Map<String, String> addEditNoteAr = {
  'addNewNote': 'إضافة مذكرة جديدة',
  'editNote': 'تعديل مذكرة',
  'tapToSelectDate': 'اضغط لاختيار التاريخ',
  'noteId': 'رقم المذكرة',
  'enterNoteId': 'أدخل رقم المذكرة',
  'noteTitle': 'عنوان المذكرة',
  'enterNoteTitle': 'أدخل عنوان المذكرة',
  'noteDescription': 'وصف المذكرة',
  'enterNoteDescription': 'أدخل وصف المذكرة',
  'noteStatus': 'حالة المذكرة:',
  'add': 'إضافة',
  'idAlreadyExist': 'رقم المذكرة موجود بالفعل!',
  'pleaseAddDifferentNoteID': 'الرجاء إدخال رقم مذكرة مختلف.',
  'noImageSelected': 'لم يتم إختيار صورة!',
  'pleaseSelectNoteImage': 'الرجاء إدخال صورة المذكرة.',
  'noDateSelected': 'لم يتم إختيار تاريخ!',
  'pleaseSelectNoteDate': 'الرجاء إدخال تاريخ المذكرة.',
  'noStatusSelected': 'لم يتم إختيار الحالة!',
  'pleaseSelectNoteStatus': 'الرجاء اختيار حالة المذكرة.',
};
