Map<String, String> addEditNoteEn = {
  'addNewNote': 'Add New Note',
  'editNote': 'Edit Note',
  'tapToSelectDate': 'Tap to select date',
  'noteId': 'Note ID',
  'enterNoteId': 'Enter Note ID',
  'noteTitle': 'Note Title',
  'enterNoteTitle': 'Enter Note Title',
  'noteDescription': 'Note Description',
  'enterNoteDescription': 'Enter Note Description',
  'noteStatus': 'Note Status:',
  'add': 'Add',
  'idAlreadyExist': 'ID already exist!',
  'pleaseAddDifferentNoteID': 'Please add different note ID.',
  'noImageSelected': 'No image selected!',
  'pleaseSelectNoteImage': 'Please select note image.',
  'noDateSelected': 'No date selected!',
  'pleaseSelectNoteDate': 'Please select note date.',
  'noStatusSelected': 'No status selected!',
  'pleaseSelectNoteStatus': 'Please select note status.',
};
